# Data
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sage'
#module: 'sage'
hidden_size: 256
num_layers: 3
nbr_neighbors: [15,10,5]
#k_hops: 5

# Regularization
dropout: 0.3

# Training
#optimizer: 'single_adam'
optimizer: 'adam_sage'
learning_rate: 0.001
weight_decay: 0.0005

max_epochs: 15
batch_size: 1024
num_workers: 1

# Device
no_cuda: False
