# Data
data_type: 'network'
dataset_name: 'random'
data_dir: './data'
task_type: 'classification'

# Param
nbr_nodes: 30
edge_prob: 0.3
nbr_features: 2
nbr_classes: 3
# Seed
seed: 1232


# Graph attention
graph_edge_module: 'gat2'
gat_nhead: 1
gat_alpha: 0.2
hidden_size: 16
gat_out_act: 'elu'

# Rewire
rewire_ratio: 0.3

# Regularization
dropout: 0.5

# Graph regularization
alpha: 1
beta: 1
gamma: 1
# Graph combining
lambda: 0.7

# Training
type_train: 'dky'
optimizer: 'adam'
criterion: 'cross-entropy-loss'
learning_rate: 0.01
weight_decay: 0.0005
max_iter: 15
batch_size: 1

# Device
no_cuda: False
# Draw
draw_graph: False 