# Data
aaa_comment: 'proj head, bs 1024'
batch_id: 8
data_dir: '../data'
dataset_name: 'ogbn-products'
#task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sageFC'
hidden_size: 128
num_layers: 2
dropout: 0.5
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'contrastive'

# Training
optimizer: 'adam'
learning_rate: 0.001
next_lr: 0.001

max_epochs: 30
batch_size: 1024
num_workers: 1

# Device
cuda: True

# Noise
noise_rate: 0.45
noise_type: 'next_pair'

# Algo
algo_type: 'contrastive'
do_warmup: True
warmup: 15
lambda: 2
ct_tk: 5
ct_tau: 1.1

# Augmentation
augment_edge: True
augment_feat: True
prob_s: 0.2
prob_l: 0.7