# Data
data_type: 'network'
dataset_name: 'random'
data_dir: './data'
task_type: 'classification'

# Param
nbr_nodes: 16
edge_prob: 0.2
nbr_features: 2
nbr_classes: 3



seed: 1232


# Graph attention
graph_module: 'gat'
gat_nhead: 2
gat_alpha: 0.2
hidden_size: 16

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.01
weight_decay: 0.0005
max_iter: 1
max_epochs: 15
batch_size: 4

# Device
no_cuda: False

# Draw
draw_graph: False 