# Data
data_type: 'network'
data_dir: '../../data'
dataset_name: 'cora'
task_type: 'classification'

# Output
out_dir: '../out/cora/ngnn'


# Seed
seed: 1232


# Graph attention
graph_edge_module: 'gat2'
module: 'simple_gcn'
nbr_neighbors: 5
gat_nhead: 1
gat_alpha: 0.2
hidden_size: 32
gat_out_act: 'elu'

# Rewire
rewire_ratio: 0.20

# Regularization
dropout: 0.5

# Graph regularization
alpha: 1
beta: 1
gamma: 1
# Graph combining
lambda: 0.5

# Training
type_train: 'dky'
optimizer: 'adam'
criterion: 'cross-entropy-loss'
learning_rate: 0.01
weight_decay: 0.0005
max_epochs: 1

batch_size: 1

# Device
no_cuda: False
# Draw
draw_graph: False 