# Data
data_type: 'network'
data_dir: '../../data'
dataset_name: 'ogbn-arxiv'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'simple_gcn'
#module: 'sage'
hidden_size: 32
num_layers: 2
nbr_neighbors: 60
k_hops: 5

# Regularization
dropout: 0.3

# Training
#optimizer: 'single_adam'
optimizer: 'adam_sage'
learning_rate: 0.01
weight_decay: 0.0005

max_epochs: 7
batch_size: 256

# Device
no_cuda: False
