# Data
batch_id: 5

data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 64
num_layers: 2
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both
compare_loss : 'normal' # normal back

# Regularization
dropout: 0.3

# Training
optimizer: 'adam'
learning_rate: 0.001 # weight_decay: 0.0005

max_epochs: 20
batch_size: 1024
num_workers: 1

# Device
cuda: True
 
# Bool
original_split: True
do_train: True
do_plot: True

# Noise
noise_rate: 0.3
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'coteaching' # ct codi cn_soft cn_hard
ct_tk: 15
ct_exp: 1
ct_tau: 1.1