# Data
batch_id: 1
data_dir: '../data'
dataset_name: 'computers'
what: '1'

# Seed
seed: 1232

# Graph model
module: 'sagePL'
hidden_size: 512
num_layers: 2
nbr_neighbors: [10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001

num_runs: 1
max_epochs: 50
batch_size: 1

# Device
cuda: True

# Bool train
do_train: True
do_plot: True
epoch_logger: False
# Bool data
load_index: True
batch_size_full: True

# Noise
noise_rate: 0.3
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'analysis' # ct codi cn_soft cn_hard
ct_tk: 25
ct_tau: 0.1

spl_cont_beta: 0.1
spl_noise_rate_neg: 0.9
spl_noise_rate_pos: 0.05
spl_rewire_rate: 0.2