# Data
batch_id: 3
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 128
num_layers: 2
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'baseline' # coteaching   baseline   both
compare_loss : 'back' # normal back

# Regularization
dropout: 0.4

# Training
optimizer: 'adam'
learning_rate: 0.001 #weight_decay: 0.0005

max_epochs: 20
batch_size: 1024
num_workers: 1

# Device
no_cuda: True
 
# Plot
do_plot: True

# Noise
noise_rate: 0.45
noise_type: 'pair' # pair   sym

# Co-teaching
ct_tk: 5
ct_exp: 1
ct_tau: 1.15