# Data
batch_id: 1
#batch_spec: 'both on noisy'

data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 128
num_layers: 2
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both
compare_loss : 'normal' # normal back

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001 # weight_decay: 0.0005

max_epochs: 25
batch_size: 1024
num_workers: 1

# Device
cuda: True
 
# Plot
do_plot: True

# Noise
noise_rate: 0.45
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'cn_soft' # ct codi cn_soft cn_hard
ct_tk: 5
ct_exp: 1
ct_tau: 1.0
co_lambda: 0.1

cn_time: 7
cn_lambda: 0.0001
cn_lambda_decay: 13