# Data
batch_id: 4
aaa_spec: "y_pure = y_pure[:batch_size],    noisy_rate=0.3     beta = 1.0  use_hard_labels=False"
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-arxiv'
task_type: 'classification'
what: '2'
# Seed
seed: 1232

# Graph model
module: 'sagePL'
hidden_size: 512
num_layers: 3
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001 # weight_decay: 0.0005

max_epochs: 30
batch_size: 512
num_workers: 1

# Device
cuda: True
 
# Bool
do_train: True
do_plot: True

# Noise
noise_rate: 0.2
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'ctp' # coteaching ctp
ct_tk: 15
ct_exp: 1
ct_tau: 1.2