# Data
batch_id: 9
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 128
num_layers: 2
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both
compare_loss : 'back' # normal back

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001 #weight_decay: 0.0005

max_epochs: 10
batch_size: 1024
num_workers: 1

# Device
no_cuda: True
 
# Plot
do_plot: True

# Noise
noise_rate: 0.35
noise_type: 'pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'cn_hard' # ct cn_soft cn_hard
cn_time: 3
cn_lambda: 0.0001
cn_lambda_decay: 8
tk: 5
ct_exp: 1
tau: 1.0