# Data
data_type: 'network'
dataset_name: 'random'
data_dir: './data'
task_type: 'classification'

# Param
nbr_nodes: 60
edge_prob: 0.2
nbr_features: 2
nbr_classes: 3



seed: 1232


# Graph attention
graph_module: 'gat'
gat_nhead: 1
gat_alpha: 0.2
hidden_size: 16

# Regularization
dropout: 0.5

# Training
type_train: 'dky'
optimizer: 'adam'
criterion: 'cross-entropy-loss'
learning_rate: 0.01
weight_decay: 0.0005
max_iter: 5
max_epochs: 15
batch_size: 1

# Device
no_cuda: False

# Draw
draw_graph: False 