# Data
batch_id: 9
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 128
num_layers: 2
dropout: 0.5
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'contrastive'

# Training
optimizer: 'adam'
learning_rate: 0.001 # weight_decay: 0.0005


max_epochs: 30
batch_size: 1024
num_workers: 1

# Device
cuda: True
 
# Plot
do_plot: True

# Noise
noise_rate: 0.4
noise_type: 'next_pair'

# Algo Co-teaching or CNCLU
algo_type: 'contrastive' # ct codi
warmup: 0
du: 0.7
tau: 5