# Data
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'
train_type: 'coteaching'
compare: True

# Seed
seed: 1232

# Graph model
module: 'gcn'
hidden_size: 64
num_layers: 2
nbr_neighbors: [15,10,5]

# Regularization
dropout: 0.4

# Training
optimizer: 'adam'
learning_rate: 0.001
weight_decay: 0.0005

max_epochs: 12
batch_size: 1024
num_workers: 1

# Device
no_cuda: True

# Plot
do_plot: True

# Noise
noise_rate: 0.4

# Co-teaching
ct_tk: 4
ct_exp: 1