# Data
batch_id: 1
aaa_spec: "graph loader 10 5"

data_type: 'network'
data_dir: '../data'
dataset_name: 'cora' #'ogbn-arxiv'
task_type: 'classification'
what: '_test2'

# Seed
seed: 1232

# Graph model
module: 'sagePL'
hidden_size: 512
num_layers: 3
#nbr_neighbors: [15,10,5]
nbr_neighbors: [10,5]

# Compare network
train_type: 'both' # nalgo   baseline   both

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001
#weight_decay: 0.0005

num_runs: 1
max_epochs: 55
batch_size: 512
num_workers: 1


# Device
cuda: True

# Bool
original_split: True
do_train: True
do_plot: False
epoch_logger: True

# Noise
noise_rate: 0.3
noise_type: 'sym' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'coteaching' # ct codi cn_soft cn_hard
ct_tk: 15
ct_exp: 1
ct_tau: 1.0

spl_cont_beta: 0.1
spl_noise_rate_neg: 0.9
spl_noise_rate_pos: 0.05
spl_rewire_rate: 0.2