# Data
batch_id: 2
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sageFC'
hidden_size: 128
num_layers: 2
dropout: 0.5
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'contrastive'

# Training
optimizer: 'adam'
learning_rate: 0.001


max_epochs: 3
batch_size: 1024
num_workers: 1

# Device
cuda: True

# Noise
noise_rate: 0.45
noise_type: 'next_pair'

# Algo
algo_type: 'contrastive'
warmup: 1
lambda: 1.0
ct_tk: 0
ct_tau: 1.1

# Augmentation
augment_edge: False
augment_feat: False
edge_prob: 0.25
feat_prob : 0.25