# Data
data_type: 'network'
dataset_name: 'random'
data_dir: './data'
task_type: 'classification'

# Param
nbr_nodes: 15
edge_prob: 0.1
nbr_features: 2
nbr_classes: 3



seed: 1232


# Graph neural networks
graph_module: 'gat'
gat_nhead: 8
gat_alpha: 0.2
hidden_size: 16

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.01
max_iter: 10
max_epochs: 15

# Device
no_cuda: False