# Data
batch_id: 10
data_dir: '../data'
dataset_name: 'computers'
what: '6'


# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 1
num_layers: 1
nbr_neighbors: [10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001
num_runs: 5
max_epochs: 150
batch_size: 1

# Device
cuda: True

# Bool train
do_train: True
do_plot: False
epoch_logger: False
# Bool data
load_index: True
batch_size_full: True

# Noise
noise_rate: 0.3
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'grid' # ct codi cn_soft cn_hard
ct_tk: 1
ct_tau: 1.0