# Data
batch_id: 2
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'
train_type: 'both'

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 128
num_layers: 2
nbr_neighbors: [5]

# Regularization
dropout: 0.3

# Training
optimizer: 'adam'
learning_rate: 0.001

max_epochs: 1
batch_size: 124
num_workers: 1

# Device
no_cuda: True

# Plot
do_plot: True

# Noise
noise_rate: 0.45
noise_type: 'pair' # pair   sym

# Co-teaching
ct_tk: 0
ct_exp: 1
ct_tau: 1