# Data
batch_id: 7
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'
train_type: 'both' # coteaching   baseline   both

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 128
num_layers: 2
nbr_neighbors: [15,10,5]

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001 #weight_decay: 0.0005

max_epochs: 25
batch_size: 1024
num_workers: 1

# Device
no_cuda: False

# Plot
do_plot: True

# Noise
noise_rate: 0.45
noise_type: 'rand_pair' # pair   sym

# Co-teaching
ct_tk: 5
ct_exp: 1
ct_tau: 1.0