# Data
batch_id: 1

data_dir: '../data'
dataset_name: 'cora' #'cora' #'ogbn-arxiv'
what: '_test2'

# Seed
seed: 1232

# Graph model
module: 'sagePL'
hidden_size: 512
num_layers: 3
nbr_neighbors: [10,5]

# Compare network
train_type: 'both' # nalgo   baseline   both

# Regularization
dropout: 0.2

# Training
optimizer: 'adam'
learning_rate: 0.005
num_runs: 3
max_epochs: 50
batch_size: 256

# Device
cuda: True

# Bool train
do_train: True
do_plot: False
epoch_logger: False
# Bool data
load_index: True
batch_size_full: True

# Noise
noise_rate: 0.4
noise_type: 'sym' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'coteaching' # ct codi cn_soft cn_hard
ct_tk: 15
ct_tau: 0.15

spl_cont_beta: 0.05
spl_noise_rate_neg: 0.9
spl_noise_rate_pos: 0.05
spl_rewire_rate: 0.2