# Data
data_type: 'network'
data_dir: './data'
dataset_name: 'ogbn-arxiv'
task_type: 'classification'

# Seed
seed: 1232


# Graph attention
graph_edge_module: 'gat2'


# Training
batch_size: 1

# Device
no_cuda: False
