# Data
batch_id: 3

data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-arxiv'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'sagePL'
hidden_size: 512
num_layers: 3
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001 # weight_decay: 0.0005

max_epochs: 15
batch_size: 512
num_workers: 1

# Device
cuda: True
 
# Bool
do_train: True
do_plot: True

# Noise
noise_rate: 0.3
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'ctp' # coteaching ctp
ct_tk: 10
ct_exp: 1
ct_tau: 1.2