# Data
batch_id: 1
data_dir: '../data'
dataset_name: 'ogbn-arxiv'
what: 'aaa'

# Seed
seed: 1232

# Graph model
module: 'sagePL'
hidden_size: 256
num_layers: 3
nbr_neighbors: [10,5]

# Compare network
train_type: 'baseline' # nalgo   baseline   both

# Regularization
dropout: 0.2

# Training
optimizer: 'adam'
learning_rate: 0.001

num_runs: 1
max_epochs: 5
batch_size: 512

# Device
cuda: True

# Bool
do_train: True
do_plot: True
epoch_logger: True

# Noise
noise_rate: 0.45
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'analysis' # ct codi cn_soft cn_hard
ct_tk: 2
ct_exp: 1
ct_tau: 1.2

spl_cont_beta: 0.1
spl_noise_rate_neg: 0.9
spl_noise_rate_pos: 0.05
spl_rewire_rate: 0.2