# Data
batch_id: 7
aaa_spec: "beta = 1.0, noisy_rate=0.1    # pseudo_pure = pseudo_pure.detach()"
aaa_spec2: "use_hard_labels=True, new_edge = topk_rewire(batch.x, batch.edge_index, self.device, k_percent=0.2)"

data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-arxiv'
task_type: 'classification'
what: '2'

# Seed
seed: 1232

# Graph model
module: 'sagePL'
hidden_size: 512
num_layers: 4
nbr_neighbors: [15,10,5]

# Compare network
train_type: 'both' # nalgo   baseline   both

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001
#weight_decay: 0.0005

max_epochs: 30
batch_size: 512
num_workers: 1

# Device
cuda: True
 
# Bool
do_train: True
do_plot: True

# Noise
noise_rate: 0.3
noise_type: 'next_pair' # pair   sym

# Algo 
algo_type: 'ctp' # coteaching ctp
ct_tk: 15
ct_exp: 1
ct_tau: 1.2