# Data
data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-products'
task_type: 'classification'

# Seed
seed: 1232

# Graph model
module: 'gcn'
hidden_size: 256
num_layers: 3
nbr_neighbors: [15,10,5]

# Regularization
dropout: 0.3

# Training
optimizer: 'adam'
learning_rate: 0.001
weight_decay: 0.0005

max_epochs: 10
batch_size: 1024
num_workers: 1

# Device
no_cuda: True

# Plot
do_plot: True

# Noise
noise_rate: 0.3

# Co-teaching
ct_tk: 6
ct_exp: 1