# Data
data_type: 'network'
dataset_name: 'cora'
data_dir: './data/cora/raw/'
task_type: 'classification'

# Output
out_dir: '../out/cora/ngnn'


seed: 1232

# Training
optimizer: 'adam'
learning_rate: 0.01
max_iter: 10
max_epochs: 15

# Device
no_cuda: False