# Data
batch_id: 4
#aaa_spec: "faire des batchs"

data_type: 'network'
data_dir: '../data'
dataset_name: 'pubmed'
task_type: 'classification'
what: '4'

# Seed
seed: 1232

# Graph model
module: 'sage'
hidden_size: 1024
num_layers: 3
#nbr_neighbors: [15,10,5]
nbr_neighbors: [10,5]

# Compare network
train_type: 'both' # nalgo   baseline   both
compare_loss : 'normal' # normal back

# Regularization
dropout: 0.3
use_bn: False

# Training
optimizer: 'adam'
learning_rate: 0.005
#weight_decay: 0.0005

num_runs: 5
max_epochs: 250
batch_size: 256
num_workers: 1

# Device
cuda: True

# Bool
original_split: True
do_train: True
do_plot: False
epoch_logger: False

# Noise
noise_rate: 0.3
noise_type: 'sym' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'coteaching' # ct codi cn_soft cn_hard
ct_tk: 100
ct_exp: 1
ct_tau: 0.2