# Data
batch_id: 1
aaa_spec: "try contrastive with sage PL"

data_type: 'network'
data_dir: '../data'
dataset_name: 'ogbn-arxiv'
task_type: 'classification'
what: '_test'

# Seed
seed: 1232

# Graph model
module: 'sagePL'
spl_noise: 0.1
rewire_rate: 0.1

hidden_size: 256
num_layers: 3 
#nbr_neighbors: [15,10,5]
nbr_neighbors: [10,5]

# Compare network
train_type: 'nalgo' # nalgo   baseline   both
compare_loss : 'normal' # normal back

# Regularization
dropout: 0.5

# Training
optimizer: 'adam'
learning_rate: 0.001
#weight_decay: 0.0005

max_epochs: 2
batch_size: 512
num_workers: 1

# Device
cuda: True

# Bool
original_split: True
do_train: True
do_plot: True

# Noise
noise_rate: 0.3
noise_type: 'next_pair' # pair   sym

# Algo Co-teaching or CNCLU
algo_type: 'coteaching' # ct codi cn_soft cn_hard
ct_tk: 1
ct_exp: 1
ct_tau: 1.2